name: C++ CI

on:
  push:
    branches: [main, parallel]
  pull_request:
    branches: [main, parallel]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install -y g++

      - name: Build with Makefile
        run: make


